;; ============================================================================
;; ========== Generated by CircuitToAcl2 using Netlist model ==================
;; ============================================================================
;;
;; * By default the outputs are placed in alphabetical order. Feel free to move
;;   things around.

(defun {{modelName}} ({{#inputs}}{{name}} {{/inputs}})
  (let* (
{{#logicGates}}
         ({{output}} ({{modelId}}{{#inputs}} {{id}}{{/inputs}}))
{{/logicGates}}
{{#blocks}}
{{#nthOutputs}}
         ({{id}} (nth {{nthId}} ({{modelId}}{{#inputs}} {{id}}{{/inputs}})))
{{/nthOutputs}}
{{/blocks}}
{{#outputs}}
         ({{name}} {{input}})
{{/outputs}}
        )
    (list{{#outputs}} {{name}}{{/outputs}})))

;; ----------------------------------------------------------------------------
;;            Proofs for correctness for {{modelName}} below
;; ----------------------------------------------------------------------------
